exit with compile failed

diff --git a/.github/workflows/openwrt-ci.yaml b/.github/workflows/openwrt-ci.yaml
--- a/.github/workflows/openwrt-ci.yaml
+++ b/.github/workflows/openwrt-ci.yaml
@@ -144,6 +144,11 @@ jobs:
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
 
+    - if: failure()
+      run: |
+        echo "Compile failed"
+        exit 1
+
     - name: Check space usage
       if: (!cancelled())
       run: df -hT
